package com.minimalisttodolist.pleasebethelastrecyclerview.util

object AnalyticsEvents {
    const val SAVE_TASK_CLICKED = "save_task_clicked"
    const val ADD_TASK_CLICKED = "add_task_clicked"
    const val MENU_CLICKED = "menu_clicked"
    const val EDIT_CLICKED = "edit_clicked"
    const val TUTORIAL_CLICKED = "tutorial_clicked"
    const val COMPLETE_TASK_CLICKED = "complete_task_clicked"
    const val REPEAT_FILTER_CLICKED = "repeat_filter_change"
    const val DUE_FILTER_CHANGE = "due_filter_change"
    const val MAYBE_REVIEW_SHOWN = "maybe_review_shown"
    const val ABOVE_0 = "above_0"
    const val ABOVE_100 = "above_100"
    const val ABOVE_200 = "above_200"
    const val ABOVE_300 = "above_300"
    const val ABOVE_400 = "above_400"
    const val ABOVE_500 = "above_500"
    const val ABOVE_600 = "above_600"
    const val ABOVE_700 = "above_700"
    const val ABOVE_800 = "above_800"
    const val ABOVE_900 = "above_900"
    const val ABOVE_1000 = "above_1000"
    const val FEEDBACK_CLICKED = "feedback_clicked"
    const val FEEDBACK_SEND_CLICKED = "feedback_SEND_clicked"
}